navs:


# 网易云音乐插件
music:
  enable: false
  # 播放器尺寸类型(1：长尺寸、2：短尺寸)
  type: 2
  # 网易云分享的音乐ID(更换音乐请更改此配置项)
  id: 554191378
  # 是否开启自动播放
  auto: false
  # 提示文本(关闭请设置为false)
  text: false

calendar:
  language: zh-CN